name: Minimum Viable Product (MVP) requirements
description: Tasks for Dedicated Mentoring Program (DMP) 2026
title: "[DMP 2026]: "
labels: ["DMP 2026"]
body:
  - type: markdown
    attributes:
      value: |
        Project Link: https://github.com/chaoss/UNSDG-classifier-tool

  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Ticket Contents
      value: |
        1. Decide on platforms to host the UN-SDG classifier tool. By hosting it, maintainers can start using this platform. Github is a good option to host static content also, and since it has a dynamic content to fetch data from third party API and get predictions from sentence transformers, hosting it on github might be tricky. Feel free to change the architecture if needed.
        2. Test out the tool for Digital Public Registry open source projects. Link: https://www.digitalpublicgoods.net/registry. Find out all the differences in SDG goals. For each project mentioned in the Digital Public Registry(DPG), it contains **SDG Relevance** section that provides the actual SDG relevance of that project. We want to test out the tool and find out the how much of the output provided by it is accuracte to the SDG Relevance of the DPG website.

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      description: List the goals of the feature. Please add the goals that must be achieved by Mid-point check-in i.e 1.5 months into the coding period.
      value: |
        ## Goals
        - A spreadsheet of test data that contains the predicted SDG relevance by the tool and the actual SDG relevance for the project
        - Figuring out ways to improve the accuracy of the tool
        - Searching for dataset or any relevant models for this project
        - Deciding on the hosting platform for the tool

  - type: textarea
    id: ticket-setup
    attributes:
      label: Setup/Installation
      description: Please list or link setup or installation guide (if any)
      value: Please go to Readme.md file and see the Manual Approach section to setup/install the project.

  - type: textarea
    id: ticket-expected-outcome
    attributes:
      label: Expected Outcome
      description: Describe in detail what the final product or result should look like and how it should behave.
      value: |
        The expected outcome for this program is to have the tool publicly accessible by everyone. Anyone should be able to access the tool and get the json or yaml output file from the tool. Also, it is expected that the output from this tool will be as close as possible to the results of SDG relevance.

  - type: textarea
    id: ticket-acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature.
      value: The acceptance criteria of this feature is to have more than 100 test results from the DPG registry.

  - type: textarea
    id: ticket-implementation-details
    validations:
      required: true
    attributes:
      label: Implementation Details
      description: List any technical details about the proposed implementation, including any specific technologies that will be used.
      value: |
        1. The architecture of the tool is Next.js for frontend and Flask for backend. For the hosting, if you find any suitable architecture along with your hosting platform, feel free to migrate to a different architecture. 
        2. For testing the tool, search for the most relevant text from each project from DPG, either from the Readme file of github repository or About section of the website of the project, and enter those details through the tool. See the json output the tool provides and make a spreadsheet of all the inputs and outputs to the system.
        3. Analyze the spreadsheet using jupyter to find out improvement section of this tool.

  - type: textarea
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: CHAOSS UN-SDG Classifier Tool
      value: CHAOSS UN-SDG Classifier Tool
    validations:
      required: true

  - type: textarea
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Enter Organisation Name
      value: CHAOSS
    validations:
      required: true
